version: '3'
services:
  mongo-server:
    image: 'mongo'
    volumes:
      - mongo-volume:/data/db
  backend-service:
    build: ./backend
    volumes:
      - music:/app/music
      - images:/app/public/images
    ports:
      - "3001:3001"
  reaper-service:
    build: ./reaper
    volumes:
      - music:/app/music

volumes:
  music:
  images:
  mongo-volume:
